apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mlalgoapp
  name: mlalgoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlalgoapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mlalgoapp
    spec:
      containers:
      - image: 420235819919.dkr.ecr.us-east-1.amazonaws.com/mlalgo4health:latest
        imagePullPolicy: IfNotPresent
        name: myhealthcareapp
        ports:
        - containerPort: 8501
          protocol: TCP
