apiVersion: v1
kind: Service
metadata:
  name: mlalgoapp
  labels:
    run: mlalgoapp
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: mlalgoapp
